### ISSUE TITLE
Server 500 Error on former multilingual sites

### ISSUE THREAD

**Issue by Teisi** [clickstorm/cs_seo#351]
500 Server error CURL Guzzle occurs on former multilingual sites.
More precisely for pages that have been translated - the translation is still available in the database, but whose TYPO3 Site-Config languages section has been deleted.
The cs_seo “Update” button probably triggers in the “Clickstorm\CsSeo\Service\FrontendPageService->getFrontendPage()” for all translations that exist in the database, regardless of whether they are still valid - i.e. whether there is even an entry for the language in the site config.

I think this behavior is triggered in the “Clickstorm\CsSeo\Command\EvaluationCommand->processResults()” method, more precisely:

```
if (!$localized) {
            $this->processResults($uid, true);
}
```

Reproducing:
- install and Config TYPO3 + Pages
- create a Page with following site config "languages" section
- create a translation of this page
- then delete the second language from the site config "languages" section
- Install cs_seo
- config cs_seo (e.g. include TypoScript)
- then click on the pages which you have created (from the step above) and click on the cs_seo "Update" - Button

then a 500 Server error CURL Guzzle occurs.

```
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle:  DE
    hreflang: de
    direction: ltr
    fallbackType: free
    fallbacks: ''
    flag: de
  -
    title: Czech
    enabled: true
    languageId: '2'
    base: /cz/
    typo3Language: default
    locale: cs_CZ.UTF-8
    iso-639-1: cs
    navigationTitle: CZ
    hreflang: cz
    direction: ltr
    fallbackType: free
    fallbacks: '0'
    flag: cz
```
